version: 2

project_name: tgforwarder

before:
  hooks:
    - go mod tidy

builds:
  - id: tgforwarder
    main: ./cmd/tgforwarder
    binary: tgforwarder
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -a
      - -trimpath
    ldflags:
     - -s -w -X cmd.version={{.Version}} -X cmd.buildDate={{.Date}} -X cmd.gitCommit={{.ShortCommit}}

archives:
  - id: tgforwarder
    builds:
      - tgforwarder
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"
